#Deploying Resources
#https://docs.aws.amazon.com/whitepapers/latest/using-power-bi-with-aws-cloud/using-power-bi-with-aws-cloud.pdf
Description: PowerBI Cloud Formation

Resources:

#Deploying Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for PowerBI Gateway
      GroupName: PowerBI
      VpcId: !Ref PowerBIVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

#Deploying VPC
  PowerBIVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key: Name 
          Value: PowerBI Gateway

#Deploying Subnet
  PowerBiPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PowerBIVPC
      AvailabilityZone: "ap-southeast-2b"
      CidrBlock: 10.0.0.0/24
      Tags:
      - Key: Name
        Value: PowerBiGateway

#Deploying EC2 Instance
  PowerBIInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: 
      InstanceType: t2.micro
      KeyName: 
      Monitoring: true
      PropagateTagsToVolumeOnCreation: 'true'
      SecurityGroupIds: 
      - !GetAtt "InstanceSecurityGroup.GroupId"
      SubnetId: !Ref PowerBiPublicSubnet
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: '5'
            DeleteOnTermination: 'false'
            Encrypted: 'false'


