#Deploying Resources
#https://docs.aws.amazon.com/whitepapers/latest/using-power-bi-with-aws-cloud/using-power-bi-with-aws-cloud.pdf
Description: PowerBI Cloud Formation

Resources:

#Deploying Security Group
  PowerBiSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for PowerBI Gateway
      GroupName: PowerBI
      VpcId: !Ref PowerBIVPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5671
          ToPort: 5671
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5672
          ToPort: 5672
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9350-9354
          ToPort: 3950-9354
          CidrIp: 0.0.0.0/0
      

#Deploying VPC
  PowerBIVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key: Name 
          Value: PowerBI Gateway

#Deploying Subnet
  PowerBiPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PowerBIVPC
      AvailabilityZone: "ap-southeast-2b"
      CidrBlock: 10.0.0.0/24
      Tags:
      - Key: Name
        Value: PowerBiGateway

#Deploying EC2 Instance
  PowerBIInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0300dc03c13eb7660
      InstanceType: t2.micro
      KeyName: Grafana3.0
      Monitoring: true
      PropagateTagsToVolumeOnCreation: 'true'
      SecurityGroupIds: 
      - !GetAtt "PowerBiSG.GroupId"
      SubnetId: !Ref PowerBiPublicSubnet
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: '10'
            DeleteOnTermination: 'false'
            Encrypted: 'false'

#Deploying Elastic IP
  PowerBiEIP:
    Type: AWS::EC2::EIP
    Properties: 
      Tags: 
        - Key: Name
          Value: PowerBIEIP



#Deploying Nat Gateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt "PowerBiEIP.AllocationId"
      ConnectivityType: public
      SubnetId: !Ref PowerBiPublicSubnet
      Tags: 
      - Key: Name 
        Value: PowerBiNatGateway
