# Cloudformation template that a VPC and public/private subnet with an RDS
# in the private subnet and an internet facing EC2 Instance


Resources:

  #VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: VPC

  #Subnet A (Public)
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: "ap-southeast-2"
      AvailabilityZoneId: "ap-southeast-2a"
      CidrBlock: "10.0.1.0"
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC # Required
      Tags:
        - Key: Name
          Value: PublicSubnetA
  
  #Subnet B (Public)
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: false
      AvailabilityZone: "ap-southeast-2"
      AvailabilityZoneId: "ap-southeast-2a"
      CidrBlock: "10.0.2.0"
      EnableDns64: false
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC # Required
      Tags:
        - Key: Name
          Value: PrivateSubnetB

  # Instance Security Group
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
      GroupDescription: 
      VpcId:
      SecurityGroupIngress:
        - Security Group Rule
      SecurityGroupEgress:
        - Security Group Rule
      Tags:
        - Key:
          Value:

  # RDS Security Group
  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
      GroupDescription: 
      VpcId:
      SecurityGroupIngress:
        - Security Group Rule
      SecurityGroupEgress:
        - Security Group Rule
      Tags:
        - Key:
          Value:

  # RDS
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      DBName: 'RDS'
      MasterUsername: 'username'
      MasterUserPassword: 'password'
      DBAllocatedStorage: 
        default: '5'
        MinValue: '1'
        MaxValue: '10'
        Type: Number